[project]
name = "nesquic"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grafanalib",
    "pyyaml>=6.0.3",
]

[tool.uv.sources]
grafanalib = { git = "https://github.com/lbrndnr/grafanalib", rev = "main" }
