[package]
name = "quiche-iut"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
bytes = "1.5.0"
tracing = "0.1.44"
quiche = "0.24.2"
url = "2.5.0"
utils = { path = "../../utils" }
tokio-quiche = "0.13.0"
tokio = { version = "1.49.0", features = ["full"] }
futures = "0.3.31"
