[package]
name = "msquic-iut"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.79"
bytes = "1.11.1"
msquic-async = { version = "0.4.0" }
tokio = "1.49.0"
tracing = "0.1.44"
utils = { path = "../../utils" }
