[package]
name = "nesquic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
built = { version = "0.8" }
clap = "4.5.23"
libbpf-rs = "0.25.0"
libc = "0.2.155"
msquic-iut = { path = "../iuts/msquic" }
quinn-iut = { path = "../iuts/quinn" }
quiche-iut = { path = "../iuts/quiche" }
tokio = { version = "1.42.0", features = ["full"] }
utils = { path = "../utils" }
tracing-subscriber = "0.3.20"
tracing = "0.1.41"
prometheus = "0.13.4"
prometheus_push = { version = "0.4.5", default-features = false, features = ["with_reqwest", "prometheus_crate"] }
lazy_static = "1.5.0"
reqwest = { version = "0.12.24", default-features = false, features = ["http2", "rustls-tls"] }
plain = "0.2.3"

[build-dependencies]
libbpf-cargo = "0.25.0"
built = { version = "0.8", features = ["cargo-lock", "dependency-tree"] }
