[package]
name = "nesquic"
version = "0.1.0"
edition = "2021"

[lib]
name = "nesquic"

[dependencies]
anyhow = "1.0.101"
built = { version = "0.8" }
clap = "4.5.59"
libbpf-rs = "0.26.0"
libc = "0.2.182"
msquic-iut = { path = "../iut/msquic" }
quinn-iut = { path = "../iut/quinn" }
quiche-iut = { path = "../iut/quiche" }
tokio = { version = "1.49.0", features = ["signal", "sync"] }
utils = { path = "../utils" }
tracing-subscriber = "0.3.22"
tracing = "0.1.44"
prometheus = "0.14.0"
prometheus_push = { version = "0.4.6", default-features = false, features = ["with_reqwest", "prometheus_crate"] }
lazy_static = "1.5.0"
reqwest = { version = "0.13.2", default-features = false, features = ["http2"] }
plain = "0.2.3"
core_affinity = "0.8.3"
futures = "0.3.32"

[build-dependencies]
libbpf-cargo = "0.26.0"
built = { version = "0.8", features = ["cargo-lock", "dependency-tree"] }

[dev-dependencies]
test-case = "3.3.1"
